version: '3.5'
services:
  sonarr:
    image: docker.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=007
      - TZ=Europe/Zurich
    volumes:
      - /var/home/core/apps/docker/sonarr/config:/config:Z
      - /var/home/core/apps/docker/sonarr/downloads:/downloads:Z
      - /mnt/shared/apps/files/series:/tv
    ports:
      - 8989:8989
    restart: 'unless-stopped'