version: '3.5'
services:
  # Needs to be run like: PODMAN_USERNS=keep-id podman-compose up
  # Until this is solved: https://github.com/containers/podman-compose/issues/166
  jellyfin:
    image: docker.io/jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - /var/mnt/shared/apps/docker/jellyfin/config:/config
      - /var/mnt/shared/apps/files/series:/data/series
      - /var/mnt/shared/apps/files/films:/data/films
      - /var/home/core/apps/docker/jellyfin/cache:/cache:Z
    environment:
      - JELLYFIN_PublishedServerUrl=192.168.31.200
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1901:1900/udp
    devices:
      - /dev/dri:/dev/dri
    restart: 'unless-stopped'
