---
version: "3.3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - JELLYFIN_PublishedServerUrl=192.168.31.200 #optional
    volumes:
      - /var/mnt/shared/apps/docker/jellyfin/config:/config
      - /var/mnt/shared/apps/files/series:/data/series
      - /var/mnt/shared/apps/files/films:/data/films
      - /var/home/core/apps/jellyfin/cache:/cache
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1901:1900/udp
    restart: unless-stopped
    privileged: true