version: '3.5'
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=007
      - TZ=Europe/Zurich
    volumes:
      - /var/home/core/apps/docker/prowlarr/config:/config:Z
    ports:
      - 9696:9696
    restart: 'unless-stopped'