version: '3'
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: hass
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /var/mnt/shared/apps/docker/homeassistant/config:/config
    # ports:
    #   - 8123:8123
    restart: unless-stopped
    privileged: true
