version: '3.5'
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=007
      - TZ=Europe/Zurich
    volumes:
      - /var/home/core/apps/docker/bazarr/config:/config:Z
      - /var/home/core/apps/files/downloads:/downloads:z
      - /mnt/shared/apps/files/films:/films
      - /mnt/shared/apps/files/series:/series
    ports:
      - 6767:6767
    restart: 'unless-stopped'