name: Docker Buton to Ignite

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        for entry in "butane"/*
        do
          filename=$(basename $entry .bu)
          docker run -i --rm quay.io/coreos/butane:release --pretty --strict < butane/$filename.bu > ignition/$filename.ign
          docker run -i --rm quay.io/coreos/ignition-validate:release - < $filename.ign
        done
        git config --global user.name 'UnconventionalMindset'
        git config --global user.email '11658632+UnconventionalMindset@users.noreply.github.com'
        git commit --allow-empty -am "Automate ignition file generation from butane"
        git push
